### ISSUE TITLE
allow setting language as cli argument

### ISSUE THREAD

**Issue by miasinterestinglife** [pcpeasant/pgsocr#2]
Currently, the language is hard-coded to English. This might not always be wanted by the user so it would be very helpful to add that as a command-line argument. 
Just a quick note: I'm not criticizing your project, I am very happy I found it, I would just wish to see it improve further as it is currently the best way of converting these subtitle files.

**Comment by pratham-tharwani** [comment]
I'll add a CLI option with the caveat that languages that have vertical writing will probably be handled incorrectly. I will try to add support for that at some point but it doesn't make sense to prevent the ability to use other languages until then.
