### ISSUE TITLE
ASS timestamps are not formatted properly

### ISSUE THREAD

**Issue by clr134** [pcpeasant/pgsocr#9]
ASS timestamps are unusual, and use centiseconds, formatted as `hh:mm:ss.cc`. pgsocr does convert the final unit correctly, but uses incorrect `h:mm:ss:cc` formatting. Despite the values being correct, incorrect formatting means editors such as Aegisub will interpret the timestamps as rapidly increasing, up to "99:99:99:99".

Suggested fix:
https://github.com/pcpeasant/pgsocr/blob/main/src/pgsocr/supconvert.py#L14 - replace final separator with `.`

**Comment by pratham-tharwani** [comment]
Fixed in commit 76fe25c. Should be resolved in the next release.
